# Generated by Django 5.0.1 on 2024-01-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_users_profile_image_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_category',
            field=models.CharField(choices=[('р', 'Ручная живопись'), ('к', 'Компьютерная живопись')], default='р', max_length=1),
        ),
    ]
